class Person {
    constructor(PID, PNAME, PAGE, PGENDER, PEMAIL, PPHONE, PADDRESS, PBLOODTYPE, PBLOODRHFACTOR, PWEIGHT, PBMI, PSMOKES, PNEARESTHOSPITAL, PDIABETESTYPE, PCOGNITIVEIMPAIREMENT, PHEARTDISEASE, PRESPIRATORYDISEASE, PMENTALILLNESS, PHASEPILEPSY, PHASHYPERTENSION, PHASOSTEOPOROSIS, PHASHIGHBLOODPRESSURE, PLASTSEIZURE, PLASTHEARTEVENT, PLASTSTROKE, PLASTHOSPITALIZATION, PALLERGIES, PCURRENTPRESCRIPTIONS, CURRENTPROBLEM, BESTSOLUTION, HOURSWITHPROBLEM) {
        this.PID = PID;
        this.PNAME = PNAME;
        this.PAGE = PAGE;
        this.PGENDER = PGENDER;
        this.PEMAIL = PEMAIL;
        this.PPHONE = PPHONE;
        this.PADDRESS = PADDRESS;
        this.PBLOODTYPE = PBLOODTYPE;
        this.PBLOODRHFACTOR = PBLOODRHFACTOR;
        this.PWEIGHT = PWEIGHT;
        this.PBMI = PBMI;
        this.PSMOKES = PSMOKES;
        this.PNEARESTHOSPITAL = PNEARESTHOSPITAL;
        this.PDIABETESTYPE = PDIABETESTYPE;
        this.PCOGNITIVEIMPAIREMENT = PCOGNITIVEIMPAIREMENT;
        this.PHEARTDISEASE = PHEARTDISEASE;
        this.PRESPIRATORYDISEASE = PRESPIRATORYDISEASE;
        this.PMENTALILLNESS = PMENTALILLNESS;
        this.PHASEPILEPSY = PHASEPILEPSY;
        this.PHASHYPERTENSION = PHASHYPERTENSION;
        this.PHASOSTEOPOROSIS = PHASOSTEOPOROSIS;
        this.HOURSWITHPROBLEM = HOURSWITHPROBLEM;
        this.PHASHIGHBLOODPRESSURE = PHASHIGHBLOODPRESSURE;
        this.PLASTSEIZURE = PLASTSEIZURE;
        this.PLASTHEARTEVENT = PLASTHEARTEVENT;
        this.PLASTSTROKE = PLASTSTROKE;
        this.PLASTHOSPITALIZATION = PLASTHOSPITALIZATION;
        this.PALLERGIES = PALLERGIES;
        this.PCURRENTPRESCRIPTIONS = PCURRENTPRESCRIPTIONS;
        this.CURRENTPROBLEM = CURRENTPROBLEM;
        this.BESTSOLUTION = BESTSOLUTION;  
    }
    
}

const p = new Person(0, "Kasey", "Suvari", 111, f, ksuvari@ptg.jp, 392419330,"61_Zane_Drive", O, +, 86, 17, 0," Prosoft_Technology_Group_Medical_Center",0,none,none,"Asthma","Anxiety",0,1,1,1,0.000,0000,0.000000,00.000000,00.000000	,none,"Zostrol & Prinivil(Lisinopril)","Back_Pain","Take NSAID(Pain reliever)")


console.log(square.area); // 100